### ISSUE TITLE
Tokenization Technique

### ISSUE THREAD

**Issue by Ahmed-Nezar** [Seif-Yasser-Ahmed/Linux-Code-Generator#1]
Is there a reason why you used character level tokenization (meaning giving each unique character an integer value)?
I think using another way of tokenization like Word2Vec (embedding) will be better as it gives the words semantic meaning (useful values) that will better for generalization or what do you think?

**Comment by Seif-Yasser-Ahmed** [comment]
Your POV of using Word2Vev instead of character level technique will surely be more effective in terms of text generation, but on the other hand character level is more powerful in terms of out-of-vocab-handling as it is capable of representing any character in the input text, like the function names and variable names, so it may be better for 'small samples of code' like the one i've used.

**Comment by Ahmed-Nezar** [comment]
Makes sense but I think you will need to test the other option to see if it will not yield a good results

**Comment by Seif-Yasser-Ahmed** [comment]
Sure, we better try other techniques, you may fork the repo to keep the results shared.
